spring.application.name: github-rest-client
server.port: 8080

feign.client.config.default.connectTimeout: 10000
feign.client.config.default.readTimeout: 10000

logging.level.pl.mwojciechowski.github.rest.client.GitHubClient: DEBUG